# Generated by Django 3.0.5 on 2020-05-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('membre1', models.CharField(max_length=100)),
                ('membre2', models.CharField(max_length=100)),
                ('membre3', models.CharField(max_length=100)),
                ('membre4', models.CharField(max_length=100)),
                ('membre5', models.CharField(max_length=100)),
                ('membre6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Nourriture'), (2, 'Hygiène'), (3, 'Nettoyage')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='forms.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Nourriture'), (2, 'Hygiène'), (3, 'Nettoyage')], default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Item')),
            ],
        ),
    ]
