# Generated by Django 3.0.5 on 2020-05-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collectivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('membre1', models.CharField(max_length=100)),
                ('membre2', models.CharField(max_length=100)),
                ('membre3', models.CharField(max_length=100)),
                ('membre4', models.CharField(max_length=100)),
                ('membre5', models.CharField(max_length=100)),
                ('membre6', models.CharField(max_length=100)),
                ('date_inscription', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('produits', models.ManyToManyField(to='forms.Product')),
            ],
        ),
    ]
