# Generated by Django 3.0.5 on 2020-05-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
