# Generated by Django 3.0.5 on 2020-05-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200514_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Item'),
        ),
    ]
