# Generated by Django 3.0.5 on 2020-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_compte_demandes'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_demande',
            field=models.DateField(auto_now=True),
        ),
    ]
