# Generated by Django 3.0.5 on 2020-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200515_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='compte',
            name='membre1',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='membre2',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='membre3',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='membre4',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='membre5',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='membre6',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='nombre',
        ),
        migrations.AddField(
            model_name='compte',
            name='ville',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte',
            name='membres',
            field=models.ManyToManyField(to='forms.Membre'),
        ),
    ]
